//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTOVENTADETA2
    {
        public long ID { get; set; }
        public int IDAUTOVENTA { get; set; }
        public int IDPRODUCTO { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal PRECIO { get; set; }
        public decimal SUBTOTAL { get; set; }
        public Nullable<int> CLIENTE { get; set; }
        public Nullable<decimal> ABONO { get; set; }
        public Nullable<decimal> COSTOAU { get; set; }
    }
}
