//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTOVENTADETA
    {
        public int ID { get; set; }
        public int IDAUTOVENTA { get; set; }
        public Nullable<int> IDPRODUCTO { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
    
        public virtual AUTOVENTA AUTOVENTA { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
