//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTOVENTADETA
    {
        public int ID { get; set; }
        public int IDAUTOVENTA { get; set; }
        public Nullable<int> IDPRODUCTO { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
    
        public virtual AUTOVENTA AUTOVENTA { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
