//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIT_ABONOSYSALDOS
    {
        public int ID { get; set; }
        public Nullable<int> IDCLUENTE { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> COBRADO { get; set; }
        public Nullable<decimal> SALDO { get; set; }
        public Nullable<long> PEDIDO { get; set; }
        public Nullable<int> REPARTIDOR { get; set; }
    
        public virtual PEDIDO PEDIDO1 { get; set; }
    }
}
