//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class BITACORAVENTASTRAB
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string CONCEPTO { get; set; }
        public string TIPO { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> COBRADO { get; set; }
        public Nullable<int> TRABAJADOR { get; set; }
    }
}
