//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAJAEXTERNA
    {
        public int ID { get; set; }
        public System.DateTime FECHA { get; set; }
        public string TIPOMOVIMIENTO { get; set; }
        public string AFECTACION { get; set; }
        public decimal IMPORTE { get; set; }
        public decimal SALDO { get; set; }
        public string USUARIOREGISTRA { get; set; }
        public string DETALLE { get; set; }
    }
}
