//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPRA()
        {
            this.COMPRADETA = new HashSet<COMPRADETA>();
            this.CUENTAXPAGAR = new HashSet<CUENTAXPAGAR>();
        }
    
        public long ID { get; set; }
        public Nullable<System.DateTime> FECHACOMPRA { get; set; }
        public string HORA { get; set; }
        public Nullable<System.DateTime> FECHAPAGO { get; set; }
        public Nullable<int> PROVEEDOR { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<int> FORMAPAGO { get; set; }
        public Nullable<int> USUARIO { get; set; }
        public string DOCUMENTO { get; set; }
        public Nullable<short> TIPO { get; set; }
    
        public virtual FORMAPAGO FORMAPAGO1 { get; set; }
        public virtual PROVEEDOR PROVEEDOR1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPRADETA> COMPRADETA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUENTAXPAGAR> CUENTAXPAGAR { get; set; }
    }
}
