//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTAXPAGAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUENTAXPAGAR()
        {
            this.CXPABONO = new HashSet<CXPABONO>();
        }
    
        public int IDCUENTA { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> SALDO { get; set; }
        public Nullable<long> COMPRA { get; set; }
    
        public virtual COMPRA COMPRA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CXPABONO> CXPABONO { get; set; }
    }
}
