//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTAXPAGAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUENTAXPAGAR()
        {
            this.CXPABONO = new HashSet<CXPABONO>();
        }
    
        public int IDCUENTA { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> SALDO { get; set; }
        public Nullable<long> COMPRA { get; set; }
    
        public virtual COMPRA COMPRA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CXPABONO> CXPABONO { get; set; }
    }
}
