//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIALENVASE
    {
        public int ID { get; set; }
        public string CONCEPTO { get; set; }
        public Nullable<int> PRODUCTO { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public Nullable<System.DateTime> FECHAPRESTADO { get; set; }
        public Nullable<System.DateTime> FECHADEVUELTO { get; set; }
    
        public virtual PRODUCTO PRODUCTO1 { get; set; }
    }
}
