//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIALENVASE
    {
        public int ID { get; set; }
        public string CONCEPTO { get; set; }
        public Nullable<int> PRODUCTO { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public Nullable<System.DateTime> FECHAPRESTADO { get; set; }
        public Nullable<System.DateTime> FECHADEVUELTO { get; set; }
    
        public virtual PRODUCTO PRODUCTO1 { get; set; }
    }
}
