//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTO
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<short> TIPO { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
    
        public virtual TRANSACCION TRANSACCION { get; set; }
    }
}
