//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PEDIDO()
        {
            this.PEDIDODETA = new HashSet<PEDIDODETA>();
            this.BIT_ABONOSYSALDOS = new HashSet<BIT_ABONOSYSALDOS>();
        }
    
        public long ID { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> CLIENTE { get; set; }
        public Nullable<int> USUARIO { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<int> REPCOBRO { get; set; }
    
        public virtual REPARTIDOR REPARTIDOR { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDODETA> PEDIDODETA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIT_ABONOSYSALDOS> BIT_ABONOSYSALDOS { get; set; }
        public virtual CLIENTE CLIENTE1 { get; set; }
    }
}
