//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.AJUSTEDETA = new HashSet<AJUSTEDETA>();
            this.COMPRADETA = new HashSet<COMPRADETA>();
            this.HISTORIALENVASE = new HashSet<HISTORIALENVASE>();
            this.PEDIDODETA = new HashSet<PEDIDODETA>();
            this.VENTADETA = new HashSet<VENTADETA>();
            this.AUTOVENTADETA = new HashSet<AUTOVENTADETA>();
        }
    
        public int ID { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> COSTO { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public string PRESENTACION { get; set; }
        public string MARCA { get; set; }
        public Nullable<decimal> EXISTENCIA { get; set; }
        public Nullable<bool> ESTADO { get; set; }
        public Nullable<bool> RETORNABLE { get; set; }
        public Nullable<decimal> STOCKMINIMO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AJUSTEDETA> AJUSTEDETA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPRADETA> COMPRADETA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIALENVASE> HISTORIALENVASE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDODETA> PEDIDODETA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENTADETA> VENTADETA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUTOVENTADETA> AUTOVENTADETA { get; set; }
    }
}
