//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALIDAEFECTIVO
    {
        public int ID { get; set; }
        public System.DateTime FECHA { get; set; }
        public string CONCEPTO { get; set; }
        public decimal IMPORTE { get; set; }
    }
}
