//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTADETA
    {
        public long ID { get; set; }
        public long VENTA { get; set; }
        public int IDPRODUCTO { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal PRECIO { get; set; }
        public decimal SUBTOTAL { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> COSTO { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
