//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTADETA
    {
        public long ID { get; set; }
        public long VENTA { get; set; }
        public int IDPRODUCTO { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal PRECIO { get; set; }
        public decimal SUBTOTAL { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> COSTO { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
