//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string HORA { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<int> USUARIO { get; set; }
        public string CONCEPTO { get; set; }
        public Nullable<int> COBRADO { get; set; }
    
        public virtual REPARTIDOR REPARTIDOR { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
