//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string HORA { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<int> USUARIO { get; set; }
        public string CONCEPTO { get; set; }
        public Nullable<int> COBRADO { get; set; }
    
        public virtual REPARTIDOR REPARTIDOR { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
