//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTASCREDITO
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string CONCEPTO { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<bool> COBRADA { get; set; }
        public Nullable<System.DateTime> FECHACOBRO { get; set; }
    }
}
