//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DEPOSITOEntities1 : DbContext
    {
        public DEPOSITOEntities1()
            : base("name=DEPOSITOEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ABONOASALDO> ABONOASALDO { get; set; }
        public virtual DbSet<AJUSTE> AJUSTE { get; set; }
        public virtual DbSet<AJUSTEDETA> AJUSTEDETA { get; set; }
        public virtual DbSet<AREAREPARTO> AREAREPARTO { get; set; }
        public virtual DbSet<AUTOVENTA> AUTOVENTA { get; set; }
        public virtual DbSet<AUTOVENTADETA2> AUTOVENTADETA2 { get; set; }
        public virtual DbSet<BITACORAVENTASTRAB> BITACORAVENTASTRAB { get; set; }
        public virtual DbSet<COMPRA> COMPRA { get; set; }
        public virtual DbSet<COMPRADETA> COMPRADETA { get; set; }
        public virtual DbSet<CUENTAXPAGAR> CUENTAXPAGAR { get; set; }
        public virtual DbSet<CXPABONO> CXPABONO { get; set; }
        public virtual DbSet<FORMAPAGO> FORMAPAGO { get; set; }
        public virtual DbSet<HISTORIALENVASE> HISTORIALENVASE { get; set; }
        public virtual DbSet<MOVIMIENTO> MOVIMIENTO { get; set; }
        public virtual DbSet<NOTAS> NOTAS { get; set; }
        public virtual DbSet<PEDIDO> PEDIDO { get; set; }
        public virtual DbSet<PEDIDODETA> PEDIDODETA { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTO { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual DbSet<REPARTIDOR> REPARTIDOR { get; set; }
        public virtual DbSet<SALIDAEFECTIVO> SALIDAEFECTIVO { get; set; }
        public virtual DbSet<SUCURSAL> SUCURSAL { get; set; }
        public virtual DbSet<TIPOUSUARIO> TIPOUSUARIO { get; set; }
        public virtual DbSet<TRANSACCION> TRANSACCION { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<VENTA> VENTA { get; set; }
        public virtual DbSet<VENTADETA> VENTADETA { get; set; }
        public virtual DbSet<VENTASCREDITO> VENTASCREDITO { get; set; }
        public virtual DbSet<BIT_ABONOSYSALDOS> BIT_ABONOSYSALDOS { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<AUTOVENTADETA> AUTOVENTADETA { get; set; }
    }
}
